### ISSUE TITLE
Support ADC class

### ISSUE THREAD

**Issue by erjac77** [f5devcentral/ansible-role-f5_atc_deploy_declaration#11]
ISSUE TYPE
  - Feature Idea

I tried to post an ADC declaration, put it failed with the following message:
`The specified atc_service is not valid`

It works using Postman.

ADC class references:
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#adc
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/composing-a-declaration.html#adc-class

**Comment by erjac77** [comment]
OK, manually setting the `atc_service` to AS3 fixed the problem. I think this should be clarify in the documentation/README.

Thank you.

**Comment by focrensh** [comment]
Just to clear, you did not originally have the AS3 class as part of the declaration?

**Comment by erjac77** [comment]
Exactly. I only had an ADC class at the root. It's a valid use case, when deploying common/shared objects for example.
