### ISSUE TITLE
Support for jinja template

### ISSUE THREAD

**Issue by xbill42** [f5devcentral/ansible-role-f5_atc_deploy_declaration#13]
ISSUE TYPE

For my understanding it looks like the POST of an AS3 does not work with jinja templates.

**Comment by focrensh** [comment]
Generation of the payload could be done with JINJA2 in a task before being called by atc_deploy.

**Comment by focrensh** [comment]
This was added in recent releases:
atc_declaration: "{{ lookup('template', 'decl.json') }}"
