### ISSUE TITLE
All GET calls broken after introduction check_teem parameter

### ISSUE THREAD

**Issue by boeboe** [f5devcentral/ansible-role-f5_atc_deploy_declaration#25]
All GET calls are broken after the introduction of the "check_teem" parameter.

**Step to reproduce:**

    - name: Verify DO licensing
      include_role:
        name: f5devcentral.atc_deploy
      vars:
        atc_method: GET
        atc_service: Device
        atc_delay: 20
        atc_retries: 60

**Error traces:**

    TASK [f5devcentral.atc_deploy : check as3 declaration and include teem data if needed] ******************************************************************************************************************
    fatal: [ec2-52-211-198-127.eu-west-1.compute.amazonaws.com]: FAILED! =>
      msg: |-
        The task includes an option with an undefined variable. The error was: 'atc_declaration' is undefined

        The error appears to be in '/Users/vanbos/.ansible/roles/f5devcentral.atc_deploy/tasks/main.yaml': line 77, column 3, but may
        be elsewhere in the file depending on the exact syntax problem.

        The offending line appears to be:

        - name: check as3 declaration and include teem data if needed
          ^ here

The bug is in the following ansible task:
https://github.com/f5devcentral/ansible-role-f5_atc_deploy_declaration/blob/565a03e31e44750736c381ebbdd733d7e372f652/tasks/main.yaml#L77

    - name: check as3 declaration and include teem data if needed
      teem_check:
        atc_json_data: "{{ atc_declaration }}"
        atc_version: "{{ atc_response.json }}"
      register: result
      when: check_teem

**Workaround:**

- Step back to a previous version of this ansible galaxy module
- Disable check_teem to avoid unintended verification of atc_declaration

**Impact:**

All customers that do an upgrade of their F5 atc_deploy ansible galaxy module

**Comment by focrensh** [comment]
Resolved in #23 

Updating tag and pushing to galaxy.
