### ISSUE TITLE
Include a VERSION file to help bug reporting

### ISSUE THREAD

**Issue by alonsocamaro** [f5devcentral/ansible-role-f5_atc_deploy_declaration#34]
Hi

I find it would be useful to have a VERSION file in role's directory so we would be able to report the version we are running.

Thanks for this great ansible code

**Comment by focrensh** [comment]
Is there a reason you need a file and cannot use the native command to see it?
(.venv) red-env $ ansible-galaxy role list
- f5devcentral.atc_deploy, v0.12.0

**Comment by alonsocamaro** [comment]
Oki, I should have installed it with ansible-galaxy then... in my case I just downloaded it and put it in the roles/ directory

**Comment by focrensh** [comment]
Ah, makes sense. Yes you should use galaxy if possible, otherwise it would just be the git commit/tag.
