### ISSUE TITLE
Missing "loginProviderName":"tmos" in authentication.yaml

### ISSUE THREAD

**Issue by cdd2** [f5devcentral/ansible-role-f5_atc_deploy_declaration#8]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

f5_atc_deploy_declaration

More specifically, 'tasks/authentication.yaml'

##### ANSIBLE VERSION

```
ansible 2.9.0
  config file = None
  configured module search path = ['/Users/s006000/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/s006000/repos/ansible-role-f5/venv/lib/python3.7/site-packages/ansible
  executable location = /Users/s006000/repos/ansible-role-f5/venv/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 18:13:23) [Clang 10.0.1 (clang-1001.0.46.4)]
```

##### PYTHON VERSION

```
Python 3.7.4
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       2.0.276
  Edition     Hotfix HF2
  Date        Sat Nov 11 04:32:09 PST 2017
```

##### OS / ENVIRONMENT

macOS Mojvae - 10.14.4

##### SUMMARY

The authentication token returned is not valid for AS3 declarations because it is the following line in the body section:
* loginProviderName: tmos

I believe this is necessary in most enterprise environments.

https://github.com/f5devcentral/ansible-role-f5_atc_deploy_declaration/blob/8e9b12aabc3ef72351083a1432a58e0256dcbf76/tasks/authentication.yaml#L3-L13

**Comment by focrensh** [comment]
Thank you, this has been resolved with c82425bad788d29206e070194bcf39a8ee8a64f4
